Remove write from access rights and add destroy right
3Stones-io/omedis pull request #396
Opened 2024-11-26 14:34 UTC by kagure-nyakio

Fixes #387

2024-11-26 15:56 UTC, almirsarajcic requested changes

2024-11-26 15:56 UTC, almirsarajcic commented on lib/omedis/accounts/can_update_organisation.ex
> +          destroy && exists(group.group_memberships, user_id == ^actor.id)
```elixir
def match?(actor, %{subject: %{data: organisation, action: %{type: action_type}}}, _opts)
      when action_type in [:update, :destroy] do
    Ash.exists?(
      filter(
        AccessRight,
        resource_name == "Organisation" and
          field(^action_type) and
          exists(group.group_memberships, user_id == ^actor.id)
      ),
      tenant: organisation
    )
  end
```
<img width="516" alt="Screenshot 2024-11-26 at 16 54 55" src="https://github.com/user-attachments/assets/95a5bcaf-d84d-418b-8081-33771aa2e39b">

2024-11-26 15:56 UTC, almirsarajcic commented on lib/omedis/accounts/checks/can_access_resource.ex
> +  def match?(
Similar to above.

2024-11-27 01:26 UTC, kagure-nyakio commented on lib/omedis/accounts/checks/can_access_resource.ex
> +  def match?(
I have already tried this. It doesn't work. Field(https://hexdocs.pm/ash/Ash.Resource.Info.html#field/2) returns an Ash.Resource.Info struct with the details of the attribute.

2024-11-27 12:11 UTC, almirsarajcic commented on lib/omedis/accounts/checks/can_access_resource.ex
> +  def match?(
Ok. Find a solution that works.

2024-11-28 09:38 UTC, almirsarajcic commented
@kagure-nyakio

2024-11-28 14:47 UTC, almirsarajcic commented on lib/omedis/accounts/can_update_organisation.ex
> +          destroy && exists(group.group_memberships, user_id == ^actor.id)
@kagure-nyakio, you missed tihs.

2024-11-28 15:53 UTC, almirsarajcic approved these changes

2024-11-28 15:53 UTC, merged