Cannot register a user in an empty database
3Stones-io/omedis pull request #408
Opened 2024-12-01 10:14 UTC by kagure-nyakio

Fixes #382 

https://github.com/user-attachments/assets/c6255217-50c9-4e0b-b497-745892e10c8c

2024-12-02 17:11 UTC, almirsarajcic requested changes

2024-12-02 17:11 UTC, almirsarajcic commented on lib/omedis_web/live/invitation_live/show.ex
> +                <.input
I didn't notice it earlier, but this is a potential security hole and since you made the original form, let's change this.

If you'd rather do it outside of this PR, go for it. Create a new task and check every form for this issue.

We shouldn't rely on client-side data for these kinds of things. Can we store this inside the LiveView socket instead?

2024-12-02 17:11 UTC, almirsarajcic commented on lib/omedis_web/live/register_live.ex
> +     |> assign(:action, "/auth/user/password/register/")
Why do we store this in the socket? Does it ever change? Also, use verified routes.

2024-12-03 16:36 UTC, kagure-nyakio commented on test/omedis_web/live/invitation_live/show_test.exs
> +      assert Ash.CiString.value(user.email) == @valid_registration_params["email"]
The comparison fails when I compare a string email to the one in the DB

2024-12-03 16:37 UTC, kagure-nyakio commented on test/omedis_web/live/invitation_live/show_test.exs
>    @valid_registration_params %{
Discussed. I gathered that we will redirect users to edit their profiles after registration.

2024-12-03 18:00 UTC, kagure-nyakio commented
@almirsarajcic, I have some questions regarding this(especially the conflicts I am facing due to the Ash Authentication flow). If you have some time, I would like to talk with you about it.

2024-12-04 09:37 UTC, almirsarajcic commented
Please write them down here. If there's a need, we can talk later.

2024-12-04 12:43 UTC, kagure-nyakio commented
I noticed that when we follow the flow for Ash Authentication, the `create` function is never called. (I think they use functions from https://hexdocs.pm/ash_authentication/3.1.0/AshAuthentication.Strategy.html for the sign-up process.) Therefore, I am unsure where to register an organisation in this flow.

The flow is also different from what you were talking about, (where you register the user before setting trigger action == true to redirect). 

Can we go outside of Phoenix Ash Authentication for this flow?

2024-12-04 14:24 UTC, almirsarajcic commented
We use `register_with_password` (https://github.com/search?q=repo%3A3Stones-io%2Fomedis%20register_with_password&type=code).

Amos has figured out how to put a trigger for that and has done it in this PR: https://github.com/3Stones-io/omedis/pull/411.
https://github.com/3Stones-io/omedis/blob/36b6a61789446dc4a4a978bc7d2c400df82e4099/lib/omedis/accounts/user.ex#L123-L131

If there's anything else, try posting on ElixirForum.

2024-12-05 09:27 UTC, kagure-nyakio commented on test/omedis_web/live/organisation_live/index_test.exs
> -      assert show_live
No

2024-12-06 16:06 UTC, almirsarajcic commented
@kagure-nyakio, don't forget to merge `main`.

2024-12-09 09:52 UTC, almirsarajcic requested changes
A minor thing + one unresolved comment above.

2024-12-09 09:52 UTC, almirsarajcic commented on test/omedis/user_test.exs
> +        |> Ash.read_one!(tenant: organisation.id, authorize?: false)
I see this in another test as well.
You can extract it out.

2024-12-09 09:52 UTC, almirsarajcic commented on test/omedis_web/live/invitation_live/show_test.exs
>    @valid_registration_params %{
Is there a test for this?

2024-12-10 08:49 UTC, almirsarajcic commented
Amos has fixed tests in https://github.com/3Stones-io/omedis/pull/429, so make sure not to overwrite his changes during the merge.

2024-12-10 08:52 UTC, almirsarajcic requested changes
Merge `main`. Otherwise, looks good.

2024-12-10 08:52 UTC, almirsarajcic commented on test/omedis/accounts/invitation_test.exs
> -    test "returns an error if invitation has expired", %{
I don't think this is the way to fix tests. Merge `main` - Amos has fixed it properly.

2024-12-10 09:43 UTC, kagure-nyakio commented on test/omedis/accounts/invitation_test.exs
> -    test "returns an error if invitation has expired", %{
Some of the tests are not fixed. Like this one. There is already a check that no one can create an invitation with a date in the past, so this test will always fail.

2024-12-10 10:16 UTC, almirsarajcic commented on test/omedis/accounts/invitation_test.exs
> -    test "returns an error if invitation has expired", %{
@amos-kibet?

2024-12-10 10:28 UTC, almirsarajcic commented on test/omedis/accounts/invitation_test.exs
> -    test "returns an error if invitation has expired", %{
Thanks

2024-12-10 10:30 UTC, almirsarajcic commented
I see 5 merge commits. This is the problem with long-running branches.
You've probably spent more time fixing conflicts than you would if you've divided this into multiple tasks.
Let's use this PR as a reference so we don't repeat the same mistake in the future.

CC: @amos-kibet, @kagure-nyakio

2024-12-10 13:23 UTC, almirsarajcic requested changes

2024-12-10 13:23 UTC, almirsarajcic commented on test/omedis/user_test.exs
> +  require Ash.Query
No need for this anymore.

2024-12-10 14:15 UTC, kagure-nyakio commented
@amos-kibet, this one too: https://github.com/3Stones-io/omedis/blob/ba5d372eeaa09cc0dd2798df5cbc06f58ea48e3c/test/omedis_web/live/invitation_live/show_test.exs#L91

2024-12-10 14:46 UTC, almirsarajcic requested changes
Tests pass on `main`.

2024-12-10 14:46 UTC, almirsarajcic commented on test/omedis_web/live/invitation_live/show_test.exs
> +      # TODO: Verify user is added to the users group
Why doesn't it work anymore?

2024-12-10 14:46 UTC, almirsarajcic commented on lib/omedis/accounts/can_create_organisation.ex
> -  def match?(%User{current_organisation_id: nil} = _actor, _context, _options) do
Is this the cause?

2024-12-10 14:46 UTC, almirsarajcic commented on test/omedis/user_test.exs
> +  require Ash.Query
Still there.

2024-12-10 15:23 UTC, kagure-nyakio commented on lib/omedis/accounts/can_create_organisation.ex
> -  def match?(%User{current_organisation_id: nil} = _actor, _context, _options) do
This was related to a different test

2024-12-10 15:25 UTC, kagure-nyakio commented
There are other references to Query functions in user test that were introduced when I did the test

2024-12-10 15:26 UTC, kagure-nyakio commented on test/omedis_web/live/invitation_live/show_test.exs
> +      # TODO: Verify user is added to the users group
The group membership list is empty and I don't see any after_action code to add invitees to groups.
I can see an issue has been created to fix this though: https://github.com/3Stones-io/omedis/issues/432(Maybe the test is ahead of it's code)

2024-12-11 11:46 UTC, merged