Update invitation user ID when invited user creates an account
3Stones-io/omedis pull request #411
Opened 2024-12-02 12:28 UTC by amos-kibet

Resolves #404.

2024-12-02 14:10 UTC, amos-kibet commented
I haven't figured out how to handle these errors; they are probably being caused by `InvitationUserLinker` GenServer. I am manually starting it in test env, and I assert on its broadcast in tests. @almirsarajcic, fter the GenServer finishes updating the invitation, is it possible to "tell" it not to talk to the DB again, until another user registers via invitation (it receives a broadcast in this case)?
```
Running ExUnit with seed: 607664, max_cases: 20

...........................................................................................................................................................................................................................17:00:54.991 [error] Postgrex.Protocol (#PID<0.899.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.2436.0> exited
............................17:00:56.001 [error] Postgrex.Protocol (#PID<0.897.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.2677.0> exited
......17:00:56.033 [error] Postgrex.Protocol (#PID<0.901.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.2707.0> exited
.17:00:56.036 [error] Postgrex.Protocol (#PID<0.886.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.2713.0> exited
```

2024-12-02 14:34 UTC, amos-kibet commented
> I haven't figured out how to handle these errors; they are probably being caused by `InvitationUserLinker` GenServer. I am manually starting it in test env, and I assert on its broadcast in tests. @almirsarajcic, fter the GenServer finishes updating the invitation, is it possible to "tell" it not to talk to the DB again, until another user registers via invitation (it receives a broadcast in this case)?
> 
> ```
> Running ExUnit with seed: 607664, max_cases: 20
> 
> ...........................................................................................................................................................................................................................17:00:54.991 [error] Postgrex.Protocol (#PID<0.899.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.2436.0> exited
> ............................17:00:56.001 [error] Postgrex.Protocol (#PID<0.897.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.2677.0> exited
> ......17:00:56.033 [error] Postgrex.Protocol (#PID<0.901.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.2707.0> exited
> .17:00:56.036 [error] Postgrex.Protocol (#PID<0.886.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.2713.0> exited
> ```

Tried this on my `setup` block:
```elixir
{:ok, pid} = start_supervised(Omedis.Accounts.InvitationUserLinker)

    on_exit(fn ->
      Process.exit(pid, :shutdown)
    end)
```
but it still doesn't work. Maybe I should [browse X](https://x.com/thmsmlr/status/1863425206133379231) for more ideas :D

2024-12-02 15:53 UTC, almirsarajcic commented
We can take a look at it together tomorrow.

2024-12-03 08:20 UTC, amos-kibet commented
> I have one semi-flaky test (seed = **921250**), then this PR is ready for review.

Same test now fails on another PR. I have added it to the flaky tests issue (#416 ).

2024-12-04 08:34 UTC, amos-kibet commented
@almirsarajcic should I broadcast when an invitation is accepted or expired, so that the UI can update in realtime? Or is that not necessary?

2024-12-04 08:46 UTC, amos-kibet commented on config/config.exs
> +config :omedis, env: config_env()
Maybe remove this. It was used to determine the current environment, in order to enable starting the Invitation GenServer only in test environment. Now that we're not using the GenServer anymore, this is unnecessary.

2024-12-04 08:46 UTC, amos-kibet commented on lib/omedis/accounts/invitation.ex
> +      accept [:email, :language, :creator_id, :inserted_at, :user_id]
Figure out if it's possible to reuse the action that updates invitation status to accepted, then there's no need to pass `user_id` here anymore.

2024-12-04 08:46 UTC, amos-kibet commented on test/omedis/user_test.exs
> +  use Omedis.DataCase, async: false
Maybe revert this.

2024-12-04 08:46 UTC, amos-kibet commented on test/omedis_web/live/invitation_live/show_test.exs
> +  use OmedisWeb.ConnCase, async: false
Maybe revert this.

2024-12-04 08:46 UTC, amos-kibet commented on test/omedis_web/live/register_test.exs
> +  use OmedisWeb.ConnCase, async: false
Maybe `async: true`?

2024-12-04 11:39 UTC, amos-kibet commented on lib/omedis/accounts/invitation.ex
> +      accept [:email, :language, :creator_id, :inserted_at, :user_id]
I'll wait and see what the community thinks about this, here: https://elixirforum.com/t/passing-other-attributes-to-actions-used-by-ashstatemachine/67875

2024-12-04 14:27 UTC, almirsarajcic commented on lib/omedis/accounts/invitation.ex
> +      accept [:email, :language, :creator_id, :inserted_at, :user_id]
Ah, I didn't understand initially what the problem was, but after I've read your question on ElixirForum, I think `:actor` can help in this case.

2024-12-04 15:08 UTC, amos-kibet commented on lib/omedis/accounts/invitation.ex
> +      accept [:email, :language, :creator_id, :inserted_at, :user_id]
Found help!

2024-12-04 15:24 UTC, almirsarajcic commented on lib/omedis/accounts/invitation.ex
> +      accept [:email, :language, :creator_id, :inserted_at, :user_id]
I don't feel like I deserve that thanks in the forum, though :D
Zach's answer was more constructive.

2024-12-04 15:27 UTC, almirsarajcic commented on config/config.exs
> +config :omedis, env: config_env()
I've become obsolete.

2024-12-04 15:28 UTC, almirsarajcic commented
> @almirsarajcic should I broadcast when an invitation is accepted or expired, so that the UI can update in realtime? Or is that not necessary?

It's gonna be a different task:
https://github.com/3Stones-io/omedis/issues/420 🌿

2024-12-04 15:29 UTC, almirsarajcic commented on test/omedis_web/live/register_test.exs
> +  use OmedisWeb.ConnCase, async: false
Can't get enough of these 😃

2024-12-04 15:55 UTC, almirsarajcic requested changes
I see you've written a lot of tests.
Can you, as a sign of triumph, increase the required coverage in `coveralls.json`? 😁

2024-12-04 15:55 UTC, almirsarajcic commented on lib/omedis_web/live/invitation_live/index.ex
> +              <span
Seems like a candidate for a component. With that, you can pattern match on the status.

2024-12-04 15:55 UTC, almirsarajcic commented on lib/omedis_web/live/invitation_live/show.ex
> +                    readonly
Can this be overriden somehow from the client-side? Should we overwrite it when submitting the form?

2024-12-04 15:55 UTC, almirsarajcic commented on lib/omedis_web/live/invitation_live/show.ex
> +      invitation ->
`nil` will be caught by this. Do we want that?

2024-12-04 15:55 UTC, almirsarajcic commented on priv/repo/migrations/20241203111756_add_state_to_invitations.exs
> +      add :status, :text, null: false, default: "pending"
Not sure about this, but maybe we can use enum type.
I was looking at Oban code and they've created their own type. Maybe we shouldn't do that, but at least we should know what the alternative is:
https://github.com/oban-bg/oban/blob/5de936606e604c681f8aed70c3e96eb4fba8301d/lib/oban/migrations/postgres/v09.ex#L28-L36
https://github.com/oban-bg/oban/blob/5de936606e604c681f8aed70c3e96eb4fba8301d/lib/oban/migrations/postgres/v09.ex#L39

Or maybe this:
https://hexdocs.pm/ecto/Ecto.Enum.html

2024-12-04 15:55 UTC, almirsarajcic commented on test/omedis_web/live/register_test.exs
> +    test "updates the associated invitation when user is created", %{
What happens when the user tries to accept an invitation, but has already registered (directly - new organisation) after the invitation was sent?

2024-12-04 15:55 UTC, almirsarajcic commented on test/omedis_web/live/invitation_live/show_test.exs
> +      :ok = OmedisWeb.Endpoint.subscribe("invitation:#{valid_invitation.id}")
I guess you're using this topic only in tests, but I think it would be more valuable to have organisation ID in the topic. Anyway, maybe no need to change it here, but keep that in mind for the realtime updates task.

2024-12-04 15:55 UTC, almirsarajcic commented on test/omedis/accounts/invitation_test.exs
> +    test "schedules invitation expiration to run immediately if expiration time is in the past",
This one is a bit too much :D
We should rather have a validation that prevents expiry date to be set to the past.

2024-12-05 01:54 UTC, amos-kibet commented on lib/omedis_web/live/invitation_live/show.ex
> +                    readonly
Aah, yes, it can be overriden by removing the `readonly` attribute on the client-side. I have now overwritten it on the form before submitting.

2024-12-05 02:06 UTC, amos-kibet commented on lib/omedis_web/live/invitation_live/show.ex
> +      invitation ->
No, we don't. I can make the flash message generic, like **Invitation not found or expired**, so as to cover the cases where the invitation was not found, or it was found, but the `InvitationNotExpiredFilter` filter-check policy filtered it out. 
What do you think about that?

2024-12-05 02:37 UTC, amos-kibet commented on test/omedis_web/live/register_test.exs
> +    test "updates the associated invitation when user is created", %{
At the time they are registering, the invitation gets accepted, so when they try accepting the invitation by clicking on the link on their email, or by visiting the `/organisations/:slug/invitations/:id` route, they will get a flash message saying **User already registered**. I will add a test case for that in `InvitationLive.ShowTest` module.

2024-12-05 03:13 UTC, amos-kibet commented on test/omedis_web/live/invitation_live/show_test.exs
> +      :ok = OmedisWeb.Endpoint.subscribe("invitation:#{valid_invitation.id}")
Good catch! I need to remove it, since I don't use PubSub at the moment, but yes, for the future, I'll scope the topics by organisation.
Thanks.

2024-12-05 03:16 UTC, amos-kibet commented on test/omedis/accounts/invitation_test.exs
> +    test "schedules invitation expiration to run immediately if expiration time is in the past",
Hahah! I agree with adding a validation.

2024-12-05 07:58 UTC, almirsarajcic commented on lib/omedis_web/live/invitation_live/show.ex
> +      invitation ->
Sorry, I've misread the `with` statements.
It seems to work as expected.

2024-12-05 08:08 UTC, almirsarajcic commented
It takes time, hold on :P

2024-12-05 08:11 UTC, almirsarajcic approved these changes

2024-12-05 08:11 UTC, merged