mplement infinite scrolling on the sticky timetracker menu
3Stones-io/omedis pull request #422
Opened 2024-12-04 16:23 UTC by kagure-nyakio

https://github.com/user-attachments/assets/b523a5b0-1e68-4f3f-a043-0dad917ce7a1

2024-12-05 10:35 UTC, almirsarajcic commented
In your screen recording, activities change colors as you scroll.

2024-12-07 17:35 UTC, kagure-nyakio commented
https://github.com/user-attachments/assets/600dcf1c-dde0-4635-80db-ba4b9376f24a

2024-12-09 10:07 UTC, almirsarajcic commented
Can you add these activities to the demo seeds to make everyone's job easier?

2024-12-10 15:08 UTC, kagure-nyakio commented
https://github.com/user-attachments/assets/a236963d-7145-4e9a-a416-21e0e1c882e0

2024-12-10 17:57 UTC, almirsarajcic commented
I've had a similar issue. You can use https://github.com/3Stones-io/omedis/blob/main/priv/repo/personas_seeds.exs as a reference.

2024-12-11 17:43 UTC, almirsarajcic requested changes

2024-12-11 17:43 UTC, almirsarajcic commented on lib/omedis_web/live/time_tracker_live/index.ex
> +        page: [limit: 10, before: socket.assigns.first_activity_token]
Only one page option is different. Everything else is the same as for the next page. Try reducing duplication.

2024-12-11 17:43 UTC, almirsarajcic commented on lib/omedis/accounts.ex
> +    {:ok, %Ash.Page.Offset{results: activities}} =
What's the difference?
In neither case we handle the errors, so why change?

2024-12-11 17:43 UTC, almirsarajcic commented on lib/omedis/accounts.ex
> +    {:ok, %Ash.Page.Offset{results: activities}} =
Same as above.

2024-12-11 17:43 UTC, almirsarajcic commented on priv/repo/demo_seeds.exs
> +require Ash.Query
Try rerunning seeds. It will crash.
Seeds are supposed to be idempotent. Running them once or as many times as you want shouldn't make a difference.

2024-12-12 08:35 UTC, kagure-nyakio commented on lib/omedis/accounts.ex
> +    {:ok, %Ash.Page.Offset{results: activities}} =
I introduced pagination code to the read action, so I get the Struct instead of a list on the read action

2024-12-12 18:22 UTC, almirsarajcic commented on lib/omedis/accounts.ex
> +    {:ok, %Ash.Page.Offset{results: activities}} =
Ok. We agreed today to do that only in `list_paginated` action, though, so that the seeds don't fail anymore.

2024-12-13 06:08 UTC, almirsarajcic commented
@kagure-nyakio

2024-12-13 11:45 UTC, almirsarajcic requested changes
Running seeds crashes, as you mentioned.
Also, there's one unresolved comment above.

2024-12-13 11:45 UTC, almirsarajcic commented on priv/repo/demo_seeds.exs
> +# %{records: [organisation_1, organisation_2], status: :success} =
We don't need this anymore.

2024-12-13 11:45 UTC, almirsarajcic commented on lib/omedis/accounts/organisation/changes/create_organisation_defaults.ex
> +        upsert_fields: [:name],
Does it work without setting fields explicitly (setting to an empty list: `[]`)?

2024-12-13 11:45 UTC, almirsarajcic commented on lib/omedis/accounts/organisation/changes/create_organisation_defaults.ex
> +            upsert_fields: [:name, :slug, :color_code, :group_id, :project_id]
Same as above.

2024-12-13 11:45 UTC, almirsarajcic commented on lib/omedis/accounts/organisation/changes/create_organisation_defaults.ex
> +          ]
You are missing the `upsert?: true` option.

2024-12-13 17:48 UTC, almirsarajcic commented
We've decided to leave the changes in the seeds for https://github.com/3Stones-io/omedis/issues/452.

2024-12-13 18:13 UTC, almirsarajcic approved these changes

2024-12-13 18:15 UTC, merged