Invited users bugfixes
3Stones-io/omedis pull request #429
Opened 2024-12-09 14:21 UTC by amos-kibet

Resolves #424.
Resolves #428.

2024-12-09 15:47 UTC, almirsarajcic requested changes
Unfortunately, there's a merge conflict.
If it was only `coveralls.json`, I'd fix it, but I'm too lazy to deal with translation files too.
Btw., https://github.com/3Stones-io/omedis/issues/431.

Anyway, good job.
🔫🤠

2024-12-09 15:47 UTC, almirsarajcic commented on lib/omedis/accounts/checks/invitation_not_expired_filter.ex
> +    expr(status != ^:expired)
Just to make it clear, this will make invitations still working until the next cron run. I guess that's ok.
No need for any changes, just a confirmation.

2024-12-10 01:29 UTC, amos-kibet commented on lib/omedis/accounts/checks/invitation_not_expired_filter.ex
> +    expr(status != ^:expired)
That's true. The check for `expires_at` is redundant since we don't allow creating invitations that have `expires_at` value in the past, or now. Here's the check:
```elixir
if expires_at > DateTime.utc_now() do
      changeset
    else
      Ash.Changeset.add_error(changeset, [:expires_at, "expiration time must be in the future"])
end
```

2024-12-10 01:50 UTC, amos-kibet commented
> Unfortunately, there's a merge conflict. If it was only `coveralls.json`, I'd fix it, but I'm too lazy to deal with translation files too. Btw., #431.
> 
> Looking at the changes related to `expires_at`, I'd say this fixes #430 too.
> 
> Anyway, good job. 🔫🤠

Yes, it does fixes #430. I have linked it.

2024-12-10 08:46 UTC, almirsarajcic approved these changes
Thanks!

By the way, next time ship the whole MVP in one PR :P

2024-12-10 08:47 UTC, merged