Use email if user has no name
3Stones-io/omedis pull request #461
Opened 2024-12-15 09:43 UTC by kagure-nyakio

Fixes #443 

https://github.com/user-attachments/assets/cdb6123a-4b2b-4c4e-99a5-33490bb35289

2024-12-16 13:17 UTC, almirsarajcic requested changes
This should be accompanied by at least unit test(s).

2024-12-16 13:17 UTC, almirsarajcic commented on lib/omedis_web/components/general_components.ex
> +                        <% end %>
As discussed, you should implement the [`String.Chars`](https://hexdocs.pm/elixir/String.Chars.html) protocol to enable something like this:
```suggestion
                        <%= @current_user %>
```

2024-12-17 06:48 UTC, almirsarajcic requested changes

2024-12-17 06:48 UTC, almirsarajcic commented on lib/omedis_web/components/general_components.ex
> +                        <%= to_string(@current_user) %>
`to_string` is called automatically.
Have you tried my proposed solution?
```suggestion
                        <%= @current_user %>
```

2024-12-17 06:48 UTC, almirsarajcic commented on lib/omedis/accounts/user/utils.ex
> +end
Can you move this to the `User` module?
Like this:
```elixir
defmodule Omedis.Accounts.User do
  # ...

  defimpl String.Chars do
    def to_string(user) do
      if user.as_string do
        user.as_string
      else
        user.email
      end
    end
  end

  # ...
end
```

2024-12-17 06:48 UTC, almirsarajcic commented on test/omedis_web/live/edit_profile_test.exs
> +      assert html =~ "test@gmail.com"
Can you specify this a bit more precisely?
I see you're on the edit profile page and I suspect there's already an email address on that page, so this doesn't assert well on whether the email address is shown in the menu or not because there are multiple occurrences of the email address on the page.

2024-12-17 06:48 UTC, almirsarajcic commented on test/omedis_web/live/edit_profile_test.exs
> +      assert html =~ "Jane Doe"
Same as above.
Maybe you can use RegEx to include the parent/container.
Ask Cursor/Claude for help.

2024-12-17 09:06 UTC, almirsarajcic commented on lib/omedis_web/components/general_components.ex
> +                        <%= to_string(@current_user) %>
Oh I see

> In order to promote HTML safety, Phoenix templates
do not use 'Kernel.to_string/1' to convert data types to...

https://hexdocs.pm/phoenix_html/Phoenix.HTML.Safe.html

Then, I guess this is the protocol you should implement instead of the other one.

2024-12-17 10:32 UTC, almirsarajcic requested changes
You've skipped some of my comments above.

2024-12-17 10:32 UTC, almirsarajcic commented on lib/omedis/accounts/user.ex
> +      user.as_string || user.email
`user.as_string` makes us go see what that function is all about. Either rename that function to something more comprehensive like `full_name` or implement its logic here.

2024-12-17 10:32 UTC, almirsarajcic commented on lib/omedis_web/components/general_components.ex
> +                        <span id="user-email-or-name"><%= to_string(@current_user) %></span>
ID `user-name` should be sufficient.

2024-12-19 14:15 UTC, almirsarajcic requested changes
Almost there.

2024-12-19 14:15 UTC, almirsarajcic commented on lib/omedis_web/live/organisation_live/show.ex
> +            <%= @organisation.owner.full_name %>
Do we test this somewhere?

2024-12-19 16:03 UTC, kagure-nyakio commented on lib/omedis_web/live/organisation_live/show.ex
> +            <%= @organisation.owner.full_name %>
I added one for the name

2024-12-19 16:12 UTC, almirsarajcic commented on lib/omedis_web/live/organisation_live/show.ex
> +            <%= @organisation.owner.full_name %>
Thanks

2024-12-19 16:12 UTC, merged