New message notification component
3Stones-io/omedis pull request #492
Opened 2024-12-26 10:28 UTC by kagure-nyakio

Fixes #470 . 
The buttons functionality should be added when the implementation of the chat(maybe) is done as that will need some backend interaction.

<img width="397" alt="Screenshot 2024-12-26 at 13 16 12" src="https://github.com/user-attachments/assets/628ed946-2eff-4a7c-906d-fd170dec1b48" />
<img width="397" alt="Screenshot 2024-12-26 at 13 15 45" src="https://github.com/user-attachments/assets/1972d002-6bba-4b10-bb6a-222f1d78ae1a" />

2024-12-26 11:25 UTC, kagure-nyakio commented
@almirsarajcic, the code coverage percentage may have "gone down" since I have added some functional components yet to be tested. I don't know how to go about this without introducing new code that is not related to the task at hand

2024-12-26 12:31 UTC, almirsarajcic commented
> @almirsarajcic, the code coverage percentage may have "gone down" since I have added some functional components yet to be tested. I don't know how to go about this without introducing new code that is not related to the task at hand

Let's ignore these components by adding them to the `"skip_files"` of the `coveralls.json` file.

2024-12-26 12:36 UTC, almirsarajcic requested changes
You'll need to do pretty much for every new component you make.

2024-12-26 12:36 UTC, almirsarajcic commented on lib/omedis_web/components/time_tracking.ex
>    alias OmedisWeb.CoreComponents
Duplicated line

2024-12-26 12:36 UTC, almirsarajcic commented on lib/omedis_web/components/time_tracking.ex
> +  def priority_message(assigns) do
Show this component in the playground.

2024-12-26 12:36 UTC, almirsarajcic commented on coveralls.json
> +    "minimum_coverage": 85.3
Unused components should be separated from the ones that we already use so we can ignore the files they are defined in.

Then add the file where you've defined the component to the `coveralls.json` and bring this `minimum_coverage` number back up.

2024-12-26 12:36 UTC, almirsarajcic commented on lib/omedis_web/components/time_tracking.ex
> +  def priority_message_stack(assigns) do
Show the component in the playground.

2024-12-27 09:31 UTC, almirsarajcic approved these changes

2024-12-27 09:31 UTC, merged